### ISSUE TITLE
Plugins still working?

### ISSUE THREAD

**Issue by dajare** [FoxCMS-Project/FoxCMS#4]
Hi Sam - I'm interested to see you developing Wolf/Fox.

I checked the updates page, and see that you have deprecated a number of functions. I'm assuming that you will be updating the "core" plugins to make use of your new functions. One of the important plugins that was never "core" was [Tagger][1], which is still working in the last version of Wolf.

Could you check to see whether Tagger still works with Fox? It might be worth "adopting" it if you plan to keep developing Fox. My own sense is that it should probably have been brought in to "official" status still in Wolf days.

Thanks!

[1]: https://github.com/mtylerb/Tagger

**Comment by SamBrishes** [comment]
Hi, 

sorry for the REALLY late response. I don't know what to say, I can just apologize for this.

I want to re-create a number of core systems, but the old plugins should still work at least until the first major release 1.0.0 has been reached.

At the moment I'm re-writing the administration MVC including a new backend theme / structure. To accomplish and ensure the compatibility I want to re-check the most available plugins too. However, I will test and add Tagger as core plugin too, of course. 

Sincerely,
Sam.

**Comment by dajare** [comment]
Thanks, Sam! See now issue #5
